# Generated by Django 5.0 on 2024-01-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_company_user_alter_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
