# Generated by Django 5.0 on 2024-01-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_resume_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='est',
            field=models.DateField(blank=True, null=True),
        ),
    ]
