# Generated by Django 5.0 on 2024-01-04 18:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
