# Generated by Django 5.0 on 2024-01-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='proffession',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
