# Generated by Django 5.0 on 2024-01-05 06:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_resume_proffession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='proffession',
            new_name='profession',
        ),
        migrations.AddField(
            model_name='resume',
            name='about_self',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
