# Generated by Django 5.0 on 2024-01-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_company_alter_job_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='requrments',
            new_name='requirments',
        ),
    ]
