# Generated by Django 5.0 on 2024-01-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_applyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='status',
            field=models.CharField(choices=[('sort-listed', 'sort-listed'), ('Pending', 'Pending'), ('Declined', 'Declinned'), ('Accepted', 'Accepted')], default='Pending', max_length=100),
        ),
    ]
